export const siteSettingsQuery = `*[_type == "siteSettings"][0]{
  siteName,
  tagline,
  contactEmail,
  bookCallUrl,
  linkedinUrl,
  dribbbleUrl,
  location,
  heroBadge,
  heroTitle,
  heroSubtitle,
  trustedByLabel,
  venturesSidebarLabel,
  defaultSeo
}`;

export const homePageQuery = `*[_type == "homePage"][0]{
  sections[]{
    _key,
    enabled,
    sectionType,
    titleOverride
  },
  designPhilosophy,
  focusSection{
    headingLine1,
    headingLine2,
    focusAreas[]->{
      _id,
      key,
      title,
      description,
      image
    }
  },
  selectedWorksHeading,
  selectedWorksIntro,
  caseStudies[]->{
    _id,
    title,
    slug,
    client,
    role,
    years,
    pageTitle,
    metaLine,
    headline,
    summary,
    description,
    tags,
    tradeoffs,
    metrics,
    logoKey,
    heroImage,
    coverImage,
    status
  },
  stories[]->{
    _id,
    title,
    subtitle,
    body,
    caption,
    backgroundImage,
    icon
  },
  ventures[]->{
    _id,
    name,
    slug,
    url,
    tagline,
    description,
    status,
    logo
  },
  testimonials[]->{
    _id,
    quote,
    name,
    role,
    company,
    photo,
    gridCellId,
    isDefault
  },
  bio{
    heading,
    bodyLeft,
    bodyRight,
    photo
  },
  contact{
    heading,
    body,
    availabilityLabel
  }
}`;

export const caseStudyFields = `
  _id,
  title,
  slug,
  client,
  role,
  years,
  pageTitle,
  metaLine,
  headline,
  summary,
  description,
  tags,
  engagementCategories,
  tradeoffs,
  metrics,
  logoKey,
  heroImage,
  coverImage,
  status,
  sortOrder,
  showCaseStudyPage,
  lede,
  publishedLabel,
  visitUrl,
  visitLabel,
  teamMeta,
  stageMeta,
  nav[]{
    _key,
    id,
    label
  },
  sections[]{
    _key,
    id,
    title,
    paragraphs,
    table[]{
      _key,
      title,
      description
    },
    phases[]{
      _key,
      phase,
      title,
      description
    },
    features[]{
      _key,
      title,
      body
    },
    metrics[]{
      _key,
      value,
      label,
      detail
    },
    numberedList,
    media[]{
      _key,
      _type,
      alt,
      caption,
      image,
      videoUrl,
      poster
    }
  }
`;

export const worksPageQuery = `*[_type == "worksPage"][0]{
  heroLabel,
  heroTitle,
  heroSubtitle,
  loadMoreBatch,
  moreWorksTitle,
  featuredProjects[]->{${caseStudyFields}},
  moreProjects[]->{${caseStudyFields}}
}`;

export const allCaseStudiesQuery = `*[_type == "caseStudy" && status != "draft"] | order(sortOrder asc){
  ${caseStudyFields}
}`;

export const feedPostFields = `
  _id,
  title,
  slug,
  publishedAt,
  status,
  tags,
  layout,
  previewBlockCount,
  content[]{
    ...,
    _type == "feedGalleryBlock" => {
      ...,
      images[]{
        _key,
        alt,
        image
      }
    }
  },
  seo
`;

export const feedPostsQuery = `*[_type == "feedPost" && status == "published"] | order(publishedAt desc){
  ${feedPostFields}
}`;

export const feedPostBySlugQuery = `*[_type == "feedPost" && slug.current == $slug][0]{
  ${feedPostFields}
}`;

export const playgroundPageQuery = `*[_type == "playgroundPage"][0]{
  items[]{
    _key,
    itemType,
    enabled,
    x,
    y,
    width,
    zIndex,
    image,
    alt,
    videoUrl,
    poster,
    comment,
    noteTitle,
    noteBody,
    noteColor,
    linkUrl,
    linkTitle,
    linkDescription,
    linkPreviewImage
  }
}`;
