import { defineArrayMember, defineField, defineType } from "sanity";

export const caseStudy = defineType({
  name: "caseStudy",
  title: "Case study",
  type: "document",
  fields: [
    defineField({
      name: "title",
      type: "string",
      title: "Project name",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "slug",
      type: "slug",
      options: { source: "title", maxLength: 96 },
      validation: (r) => r.required(),
    }),
    defineField({ name: "client", type: "string", title: "Client / company" }),
    defineField({ name: "role", type: "string", title: "Role", description: "e.g. Design Lead" }),
    defineField({ name: "years", type: "string", title: "Years", description: "e.g. 2023–2026" }),
    defineField({
      name: "pageTitle",
      type: "string",
      title: "Page title",
      description: "SEO title and page heading. Falls back to showcase title.",
    }),
    defineField({
      name: "metaLine",
      type: "string",
      title: "Meta line",
      description: "Legacy one-liner for homepage cards, e.g. Default · B2B SaaS · 2023-2026",
    }),
    defineField({
      name: "headline",
      type: "text",
      title: "Showcase title",
      description: "Heading on the works page project card.",
      rows: 3,
    }),
    defineField({
      name: "summary",
      type: "text",
      title: "Showcase summary",
      description: "Short intro under the showcase title.",
      rows: 4,
    }),
    defineField({
      name: "description",
      type: "text",
      title: "Description",
      description: "Full project description on the works page.",
      rows: 6,
    }),
    defineField({
      name: "logoKey",
      type: "string",
      title: "Logo component",
      description: "Built-in logo for known clients. Leave empty for initials.",
      options: {
        list: [
          { title: "Default.com", value: "default" },
          { title: "Apollo.io", value: "apollo" },
          { title: "P2P.org", value: "p2p" },
          { title: "Commun", value: "commun" },
          { title: "Kinescope", value: "kinescope" },
        ],
      },
    }),
    defineField({
      name: "tags",
      type: "array",
      of: [defineArrayMember({ type: "string" })],
      options: { layout: "tags" },
    }),
    defineField({
      name: "engagementCategories",
      type: "array",
      title: "Works page filters",
      of: [defineArrayMember({ type: "string" })],
      options: {
        list: [
          { title: "Full time", value: "full-time" },
          { title: "Case studies", value: "case-studies" },
          { title: "Contract", value: "contract" },
          { title: "Concepts", value: "concepts" },
        ],
      },
    }),
    defineField({ name: "tradeoffs", type: "text", title: "Trade-offs / notes", rows: 4 }),
    defineField({
      name: "metrics",
      type: "array",
      of: [defineArrayMember({ type: "metric" })],
    }),
    defineField({ name: "heroImage", type: "image", options: { hotspot: true } }),
    defineField({
      name: "coverImage",
      type: "image",
      title: "Works page screenshot",
      description: "Primary screenshot on /works and project pages.",
      options: { hotspot: true },
    }),
    defineField({
      name: "status",
      type: "string",
      options: {
        list: [
          { title: "Published", value: "published" },
          { title: "Coming soon", value: "soon" },
          { title: "Draft", value: "draft" },
        ],
        layout: "radio",
      },
      initialValue: "published",
    }),
    defineField({
      name: "sortOrder",
      type: "number",
      title: "Sort order",
      description: "Used when not manually ordered on the homepage.",
      initialValue: 0,
    }),
    defineField({
      name: "showCaseStudyPage",
      type: "boolean",
      title: "Show case study page",
      description: "When off, /works/:slug shows “Project not found”.",
      initialValue: true,
      fieldset: "caseStudyPage",
    }),
    defineField({
      name: "lede",
      type: "text",
      title: "Case study lede",
      rows: 4,
      fieldset: "caseStudyPage",
    }),
    defineField({
      name: "publishedLabel",
      type: "string",
      title: "Published label",
      description: "e.g. 2023–2026",
      fieldset: "caseStudyPage",
    }),
    defineField({ name: "visitUrl", type: "url", title: "Visit site URL", fieldset: "caseStudyPage" }),
    defineField({ name: "visitLabel", type: "string", title: "Visit link label", fieldset: "caseStudyPage" }),
    defineField({
      name: "teamMeta",
      type: "string",
      title: "Team meta",
      description: "e.g. 2 designers, 8 engineers",
      fieldset: "caseStudyPage",
    }),
    defineField({
      name: "stageMeta",
      type: "string",
      title: "Stage meta",
      description: "e.g. Series A → Series B",
      fieldset: "caseStudyPage",
    }),
    defineField({
      name: "nav",
      type: "array",
      title: "Section navigation",
      of: [defineArrayMember({ type: "caseStudyNavItem" })],
      fieldset: "caseStudyPage",
    }),
    defineField({
      name: "sections",
      type: "array",
      title: "Case study sections",
      of: [defineArrayMember({ type: "caseStudySection" })],
      fieldset: "caseStudyPage",
    }),
  ],
  fieldsets: [
    { name: "caseStudyPage", title: "Case study page", options: { collapsible: true, collapsed: false } },
  ],
  orderings: [
    { title: "Sort order", name: "sortOrder", by: [{ field: "sortOrder", direction: "asc" }] },
  ],
  preview: {
    select: { title: "title", subtitle: "client", media: "heroImage" },
  },
});
